### ISSUE TITLE
I can't get creating a voucher to work.

### ISSUE THREAD

**Issue by itsjustnickdev** [DeathHound6/control-panel-api-wrapper#1]
My code:
```
const c = require("control-panel-api-wrapper");

const panel = new c("my domain", "my token");


// Put admin apikey here
client.on('message', msg => {
  if (msg.content === '?cvoucher') {
      
      if(!msg.member.hasPermission("ADMINISTRATOR")){
  return msg.reply("You don't have permission to do that.");
}else
    
    panel.voucherManager.createOne({
        memo: "TEST", 
        expires_at: null,
        code: "testing",
        uses: "5",
        credits: "1" 
                                   });
    
   // msg.reply('Im working on this');
      msg.delete()
  }
});
```
Error:

```
(node:2176) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://avocadonodes.com/vouchers reason: Unexpected token < in JSON at position 0
    at /home/container/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async VoucherManager.createOne (/home/container/node_modules/control-panel-api-wrapper/src/structures/VoucherManager.js:46:22)
(node:2176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DeathHound6** [comment]
Sorry for such a late response

I don't recall getting any errors like that in testing, but I'll definitely look into this

**Comment by DeathHound6** [comment]
> 
> 
> My code:
> 
> ```
> const c = require("control-panel-api-wrapper");
> 
> const panel = new c("my domain", "my token");
> 
> 
> // Put admin apikey here
> client.on('message', msg => {
>   if (msg.content === '?cvoucher') {
>       
>       if(!msg.member.hasPermission("ADMINISTRATOR")){
>   return msg.reply("You don't have permission to do that.");
> }else
>     
>     panel.voucherManager.createOne({
>         memo: "TEST", 
>         expires_at: null,
>         code: "testing",
>         uses: "5",
>         credits: "1" 
>                                    });
>     
>    // msg.reply('Im working on this');
>       msg.delete()
>   }
> });
> ```
> 
> Error:
> 
> ```
> (node:2176) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://avocadonodes.com/vouchers reason: Unexpected token < in JSON at position 0
>     at /home/container/node_modules/node-fetch/lib/index.js:272:32
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async VoucherManager.createOne (/home/container/node_modules/control-panel-api-wrapper/src/structures/VoucherManager.js:46:22)
> (node:2176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:2176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Just noticed in your error message the url is wrong. When providing this to the module, you must append `/api` to the end of your domain url

Through current testing I have noticed that creating vouchers doesn't actually seem to work on the current version of the panel, but I have informed the developers of their server-side issue and they will look into it soon

**Comment by itsjustnickdev** [comment]
alright lemme know when it works

**Comment by NotHiiragi** [comment]
Yes it would be lovely if the create voucher works
